dist: bionic
language: python
cache: pip
env:
  global:
    - LAMBDA_NAME: digitized_av_trigger

before_script:
  - pip install tox

script: tox

before_deploy:
  - pip install awscli
  - if [ ! -d deploy_scripts ]; then git clone https://github.com/RockefellerArchiveCenter/deploy_scripts.git; fi
  - sudo deploy_scripts/make_zip_lambda.sh ${LAMBDA_NAME} src/handle_digitized_av_trigger.py

deploy:
  - provider: s3
    bucket: rac-dev-cloudfront-apps
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    glob: ${LAMBDA_NAME}.template
    on:
      branch: development
  - provider: s3
    bucket: rac-prod-cloudfront-apps
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    glob: ${LAMBDA_NAME}.template
    on:
      branch: base
  - provider: s3
    bucket: rac-dev-lambda
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    glob: ${LAMBDA_NAME}.zip
    on:
      branch: development
  - provider: s3
    bucket: rac-prod-lambda
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    glob: ${LAMBDA_NAME}.zip
    on:
      branch: base
  - provider: script
    script: deploy_scripts/deploy_package_lambda.sh ${LAMBDA_NAME}
    on:
      condition: $TRAVIS_BRANCH =~ ^(base|development)$

notifications:
  email: false
