dist: bionic
language: python
cache: pip

before_script:
  - pip install tox

script: tox

deploy:
  - provider: s3
    bucket: rac-dev-cloudfront-apps
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    glob: digitized_av_trigger.template
    on:
      branch: development
  - provider: s3
    bucket: rac-prod-cloudfront-apps
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    glob: digitized_av_trigger.template
    on:
      branch: base

notifications:
  email: false
