AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  digitized-av-trigger

  Handles notifications for validation and packaging of incoming digitized audiovisual assets.

Globals:
  Function:
    Timeout: 3

Parameters:
  AudioUploadBucketName:
    Type: String
    Description: Name of an S3 bucket to which audio assets are uploaded.
  VideoUploadBucketName:
    Type: String
    Description: Name of an S3 bucket to which audio assets are uploaded.
  QcBucketName:
    Type: String
    Description: Name of a bucket into which validated assets are moved.
    Default: 'rac-av-qc'
  EcsCluster:
    Type: String
    Description: The short name or full ARN of the ECS cluster to run your task on.
    Default: 'RACCLUS'
  EcsSubnet:
    Type: String
    Description: The IDs of the subnet in which the ECS task should run.
    Default: 'subnet-0102189437e2babd8'

Resources:
  DigitizedAvTriggerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: IAM Role which supports calling ecs:RunTask.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::817658541382:policy/DigitizedAVRunECSTask
  DigitizedAvTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handle_digitized_av_trigger.lambda_handler
      FunctionName: digitized_av_trigger
      Role: DigitizedAvTriggerFunctionRole.Arn
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64
      Environment:
        Variables:
          ECS_CLUSTER:
            Ref: EcsCluster
          ECS_SUBNET:
            Ref: EcsSubnet
      Events:
        AudioEvents:
          Type: S3
          Properties:
            Bucket: !Ref AudioUploadBucket
            Events:
              - 's3:ObjectCreated:*'
        VideoEvents:
          Type: S3
          Properties:
            Bucket: 
              Ref: VideoUploadBucket
            Events:
              - 's3:ObjectCreated:*'

  AudioUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AudioUploadBucketName
  VideoUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref VideoUploadBucketName
  QcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref QcBucketName

Outputs:
  DigitizedAvTriggerFunction:
    Description: "Digitized AV Trigger Lambda Function ARN"
    Value: !GetAtt DigitizedAvTriggerFunction.Arn
