AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  digitized-av-trigger

  Handles notifications for validation and packaging of incoming digitized audiovisual assets.

Globals:
  Function:
    Timeout: 3

Parameters:
  AudioUploadBucketName:
    Type: String
    Description: Name of an S3 bucket to which audio assets are uploaded.
  VideoUploadBucketName:
    Type: String
    Description: Name of an S3 bucket to which audio assets are uploaded.
  QcBucketName:
    Type: String
    Description: Name of a bucket into which validated assets are moved.
    Default: 'rac-av-qc'

Resources:
  DigitizedAvTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handle_digitized_av_trigger.lambda_handler
      FunctionName: digitized_av_trigger
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64
      Events:
        AudioEvents:
          Type: S3
          Properties:
            Bucket: !Ref AudioUploadBucket
            Events:
              - 's3:ObjectCreated:*'
        VideoEvents:
          Type: S3
          Properties:
            Bucket: 
              Ref: VideoUploadBucket
            Events:
              - 's3:ObjectCreated:*'

  AudioUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AudioUploadBucketName
  VideoUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref VideoUploadBucketName
  QcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref QcBucketName

  #TODO IAM role that can call ecs:RunTask

Outputs:
  DigitizedAvTriggerFunction:
    Description: "Digitized AV Trigger Lambda Function ARN"
    Value: !GetAtt DigitizedAvTriggerFunction.Arn
