AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  digitized-av-trigger

  Handles notifications for validation and packaging of incoming digitized audiovisual assets.

Globals:
  Function:
    Timeout: 3

Parameters:
  EcsCluster:
    Type: String
    Description: The short name or full ARN of the ECS cluster to run your task on.
    Default: 'RACCLUS'
  EcsSubnet:
    Type: String
    Description: The IDs of the subnet in which the ECS task should run.
    Default: 'subnet-0102189437e2babd8'

Resources:
  DigitizedAvTriggerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: IAM Role which supports calling ecs:RunTask.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies: 
        - PolicyName: DigitizedAVRunECSTaskPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'ecs:RunTask'
                Resource: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/digitized_av_*'
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: '*'
                Condition:
                  StringLike:
                    'iam:PassedToService': 'ecs-tasks.amazonaws.com'
  DigitizedAvTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handle_digitized_av_trigger.lambda_handler
      FunctionName: digitized_av_trigger
      Role: !GetAtt DigitizedAvTriggerFunctionRole.Arn
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64
      Environment:
        Variables:
          ECS_CLUSTER:
            Ref: EcsCluster
          ECS_SUBNET:
            Ref: EcsSubnet

Outputs:
  DigitizedAvTriggerFunction:
    Description: "Digitized AV Trigger Lambda Function ARN"
    Value: !GetAtt DigitizedAvTriggerFunction.Arn
    Export:
      Name: DigitizedAV-TriggerArn
